# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Test_ZipDac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_ZipDac
 
  pod 'Alamofire'
  pod 'SwiftSoup'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'NVActivityIndicatorView'
  pod 'Kingfisher', '~> 5.6'

  target 'Test_ZipDacTests' do  
  inherit! :search_paths
    # Pods for testing   
  end

  target 'Test_ZipDacUITests' do
    # Pods for testing
  end

end
